### ISSUE TITLE
这里不应该是 bar.value么

### ISSUE THREAD

**Issue by Airfald** [QC2168/useCharts#1]
https://github.com/QC2168/useCharts/blob/ed5d7f4b0d63ab9f2dd868deb60333e96b1b2a37/example/src/components/Chart/index.vue#L54

**Comment by QC2168** [comment]
不是的，`useChart`中的`setOption`方法接收的是一个`EChartsOption`对象。
例子中，图表的数据是放在`barData`中的。在`axios.get('/api/bar')`之后，我们只要将获取到的数据赋值到`barData.value`中再调用`setOption`更新图表即可。（你可以通过`watch`的方式监听`option`或者`barData`的变动自动调用`setOption`）
